name: LexOS Deployment Alert

on:
  push:
    branches:
      - main

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Tactical Alert to War Room
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "👑 **COMMANDER OMG.LEXIEEE:** Roberts Ent. has successfully updated the LexOS Global Headquarters. The newest meta data and tactical UI are now live on the global network."
